backend = "glx";
vsync = true;
use-damage = true;
xrender-sync-fence = true;

# Activa las sombras
shadow = true;

# El radio del desenfoque (pruébalo en 40 o 60 para que sea enorme)
shadow-radius = 25;

# La opacidad (1.0 es el máximo, lo hará muy oscuro)
shadow-opacity = 0.8;

# El desplazamiento (ajusta estos para que la sombra se mueva hacia afuera)
shadow-offset-x = -25;
shadow-offset-y = -25;

blur-method = "dual_kawase";
blur-strength = 5;
blur-background = true;

shadow-exclude = [
    "!I3_FLOATING_WINDOW@:s",
    "_GTK_FRAME_EXTENTS@:s",
    "window_type = 'menu'",
    "window_type = 'dropdown_menu'",
    "window_type = 'popup_menu'",
    "window_type = 'tooltip'",
    "class_g = 'i3bar'"
];

blur-background-exclude = [
    "window_type = 'menu'",
    "window_type = 'dropdown_menu'",
    "window_type = 'popup_menu'",
    "window_type = 'tooltip'",
    "_GTK_FRAME_EXTENTS@:s"
];

wintypes:
{
  tooltip = { fade = true; shadow = false; opacity = 0.85; focus = true; full-shadow = false; };
  dock = { shadow = false; clip-shadow-above = true; }
  dnd = { shadow = false; }
  popup_menu = { opacity = 1.0; shadow = false; }
  dropdown_menu = { opacity = 1.0; shadow = false; }
};


